# EDA do meta-vetor

In [1]:
%load_ext autoreload

In [2]:
import numpy as np
from src.data.make_dataset import data
%autoreload 2 

## Importa o banco de dados escolhido

In [3]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
n = len(data)

Tenta fazer as fórmulas de Density
---

## $$P[r] = \frac{1}{n} \sum_{n=1}^{n} \frac{1}{h^p}\phi \bigg( \frac{d(\boldsymbol{x}_r,\boldsymbol{x}_s)}{h} \bigg)$$

Fórmula $\phi$ 
---

## $$\phi(u) = \frac{1}{\sqrt{2\pi}}e^{\frac{-u^{2}}{2}}$$

In [5]:
def phi_fn(u):
    x = 1 / np.sqrt(2 * np.pi)
    return x * np.e ** (-u ** 2 / 2)

### Vetor $P$

In [6]:
P = np.zeros(n)

### Vetor $P'$

In [7]:
P_linha = np.zeros(n)

### Matriz $Q$

In [8]:
Q = np.empty((n,n))

### $p$ variáveis

In [9]:
p = data.size
p

600

In [10]:
for r in range(n):
    for s in range(r,n):
        Q[r,s] = phi_fn(np.linalg.norm(data[r] - data[s]) / 1)

In [11]:
for r in range(n):
    P[r] = (1/n) * np.sum((1 / p) * Q[r])

In [12]:
P

array([ 1.93235354e-004,  1.77847295e-004,  1.74070259e-004,
        1.64622460e-004, -3.44821717e+094,  1.47737020e-004,
        1.37394246e+286, -6.95292371e+096,  1.25327740e-004,
        2.80625078e+091,  2.68266042e+261,  2.80551524e+065,
        5.28452302e+282,  1.46461266e+049, -4.98628611e+177,
        9.11254780e+099, -3.76279272e+252,  6.04886147e+172,
        3.09524902e+282,  1.15316693e-004,  6.21585727e+061,
        2.10754596e+019,  7.90251958e+184, -1.70805620e+276,
        1.61929055e+284,  1.18372926e+281, -1.65703412e+097,
        9.04455660e-005, -4.21221914e+287, -5.69273628e+264,
        2.28254649e+293,  7.08732607e-005,  1.71155816e+291,
       -2.10901524e+256, -1.47378970e+112, -1.38330888e+190,
        6.04415183e+298,  4.08129232e+287, -1.09071813e+111,
       -6.36785068e+292,  6.52969393e+091,  2.12898591e+245,
       -7.67652248e+199, -9.13185549e+302, -4.22167779e+264,
       -8.10831688e+169,  2.94750646e+279, -7.80422024e+235,
       -9.77779024e+274,

In [13]:
minimum, maximum = np.min(P), np.max(P)
P_linha = (P - minimum) / (maximum - minimum) 

In [14]:
P_linha

array([0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 1.        , 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.        , 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.9999355 ,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993382,
       0.99993382, 0.99993382, 0.99993382, 0.99993382, 0.99993